// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eCFguYRHmGSz9j2J0mZKiUi9vphk2L0',
    appId: '1:169566722649:web:a097854abe411973986f48',
    messagingSenderId: '169566722649',
    projectId: 'flutter-afterglow',
    authDomain: 'flutter-afterglow.firebaseapp.com',
    storageBucket: 'flutter-afterglow.firebasestorage.app',
    measurementId: 'G-YCPVVQ2Y8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrpqbHJT1NQuCGICTmx5ZI7HWXJ2rCkA',
    appId: '1:169566722649:android:76e49b7ee1b1dee2986f48',
    messagingSenderId: '169566722649',
    projectId: 'flutter-afterglow',
    storageBucket: 'flutter-afterglow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpa0Yo7yDksESW6Tu1TwUweoLTm9hm5m4',
    appId: '1:169566722649:ios:c8648d2ac2c86e3c986f48',
    messagingSenderId: '169566722649',
    projectId: 'flutter-afterglow',
    storageBucket: 'flutter-afterglow.firebasestorage.app',
    iosBundleId: 'com.example.afterglowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpa0Yo7yDksESW6Tu1TwUweoLTm9hm5m4',
    appId: '1:169566722649:ios:c8648d2ac2c86e3c986f48',
    messagingSenderId: '169566722649',
    projectId: 'flutter-afterglow',
    storageBucket: 'flutter-afterglow.firebasestorage.app',
    iosBundleId: 'com.example.afterglowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1eCFguYRHmGSz9j2J0mZKiUi9vphk2L0',
    appId: '1:169566722649:web:a097854abe411973986f48',
    messagingSenderId: '169566722649',
    projectId: 'flutter-afterglow',
    authDomain: 'flutter-afterglow.firebaseapp.com',
    storageBucket: 'flutter-afterglow.firebasestorage.app',
    measurementId: 'G-YCPVVQ2Y8E',
  );
}
